namespace ControlPlane.Api.Features.Adapters.Proxmox;

/// <summary>
/// Configuration options for automated Proxmox snapshot retention and cleanup.
/// </summary>
public class SnapshotRetentionOptions
{
    public const string SectionName = "Proxmox:Retention";

    /// <summary>
    /// Retention window in hours. Pre-update safety snapshots older than this will be pruned. Default: 24.
    /// </summary>
    public int RetentionHours { get; set; } = 24;

    /// <summary>
    /// Periodic background sweep interval in minutes. Default: 60.
    /// </summary>
    public int ScanIntervalMinutes { get; set; } = 60;

    /// <summary>
    /// Whether automated periodic snapshot pruning is enabled. Default: true.
    /// </summary>
    public bool Enabled { get; set; } = true;

    /// <summary>
    /// Prefix identifying snapshots generated by ControlPlane. Default: "cp-pre-update-".
    /// </summary>
    public string SnapshotPrefix { get; set; } = "cp-pre-update-";
}
