{{- if and .Values.networkPolicy.enabled .Values.networkPolicy.cilium.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "controlplane.fullname" . }}-api-cilium
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "controlplane.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: controlplane-api
      app.kubernetes.io/instance: {{ .Release.Name }}
  egress:
    {{- if .Values.networkPolicy.cilium.allowAllEgress }}
    - toEntities:
        - all
    {{- else }}
    {{- if or .Values.networkPolicy.cilium.toEntities .Values.networkPolicy.cilium.allowClusterNodes }}
    - toEntities:
        {{- range .Values.networkPolicy.cilium.toEntities }}
        - {{ . }}
        {{- end }}
        {{- if .Values.networkPolicy.cilium.allowClusterNodes }}
        - remote-node
        - host
        {{- end }}
    {{- end }}
    {{- range .Values.networkPolicy.allowedEgressSubnets }}
    - toCIDR:
        - {{ . }}
    {{- end }}
    {{- end }}
    {{- with .Values.networkPolicy.cilium.extraEgress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
