{{- if and .Values.networkPolicy.enabled .Values.networkPolicy.cilium.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "controlplane.fullname" . }}-api-cilium
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "controlplane.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: controlplane-api
      app.kubernetes.io/instance: {{ .Release.Name }}
  egress:
    - toEntities:
        - kube-apiserver
{{- end }}
