{{- if .Values.ingress.enabled -}}
{{- $fullName := include "controlplane.fullname" . -}}
{{- $apiServiceName := printf "%s-api" $fullName -}}
{{- $frontendServiceName := printf "%s-frontend" $fullName -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "controlplane.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ if .serviceName }}{{ .serviceName }}{{ else if eq .service "api" }}{{ $apiServiceName }}{{ else if eq .service "temporal-ui" }}{{ .temporalUiServiceName | default "temporal-ui" }}{{ else }}{{ $frontendServiceName }}{{ end }}
                port:
                  number: {{ if .port }}{{ .port }}{{ else if eq .service "api" }}8080{{ else if eq .service "temporal-ui" }}8233{{ else }}80{{ end }}
          {{- end }}
    {{- end }}
{{- end }}
