// <auto-generated />
using System;
using ControlPlane.Api.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControlPlane.Api.Migrations
{
    [DbContext(typeof(ControlPlaneDbContext))]
    [Migration("20260905032313_AddSystemSettings")]
    partial class AddSystemSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControlPlane.Api.Storage.Entities.ClusterLease", b =>
                {
                    b.Property<string>("LeaseKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lease_key");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acquired_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("HolderIdentifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("holder_identifier");

                    b.HasKey("LeaseKey")
                        .HasName("pk_cluster_leases");

                    b.ToTable("cluster_leases", (string)null);
                });

            modelBuilder.Entity("ControlPlane.Api.Storage.Entities.Host", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FriendlyName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hostname");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("OsFamily")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("os_family");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_hosts");

                    b.HasIndex("Hostname")
                        .IsUnique()
                        .HasDatabaseName("ix_hosts_hostname");

                    b.HasIndex("IpAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_hosts_ip_address");

                    b.ToTable("hosts", (string)null);
                });

            modelBuilder.Entity("ControlPlane.Api.Storage.Entities.StepLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("LogLine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("log_line");

                    b.Property<long>("SequenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_id");

                    b.Property<string>("StreamType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("stream_type");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_step_logs");

                    b.HasIndex("JobId", "SequenceId")
                        .HasDatabaseName("idx_step_logs_job_seq");

                    b.ToTable("step_logs", (string)null);
                });

            modelBuilder.Entity("ControlPlane.Api.Storage.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value_json");

                    b.HasKey("Key")
                        .HasName("pk_system_settings");

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("ControlPlane.Api.Storage.Entities.UpdateJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActiveStep")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("active_step");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("initiated_by");

                    b.Property<string>("PipelineId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pipeline_id");

                    b.Property<string>("SnapshotIdentifier")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("snapshot_identifier");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetHostId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_host_id");

                    b.HasKey("Id")
                        .HasName("pk_update_jobs");

                    b.HasIndex("TargetHostId")
                        .HasDatabaseName("ix_update_jobs_target_host_id");

                    b.ToTable("update_jobs", (string)null);
                });

            modelBuilder.Entity("ControlPlane.Api.Storage.Entities.Host", b =>
                {
                    b.OwnsOne("ControlPlane.Api.Storage.Entities.AgentState", "Agent", b1 =>
                        {
                            b1.Property<Guid>("HostId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<bool>("Installed")
                                .HasColumnType("boolean")
                                .HasColumnName("agent_installed");

                            b1.Property<DateTimeOffset?>("LastSeenAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("agent_last_seen_at");

                            b1.Property<bool>("PendingReboot")
                                .HasColumnType("boolean")
                                .HasColumnName("pending_reboot");

                            b1.Property<int>("UpgradablePackagesCount")
                                .HasColumnType("integer")
                                .HasColumnName("upgradable_packages_count");

                            b1.Property<string>("Version")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("agent_version");

                            b1.HasKey("HostId");

                            b1.ToTable("hosts");

                            b1.WithOwner()
                                .HasForeignKey("HostId")
                                .HasConstraintName("fk_hosts_hosts_id");
                        });

                    b.OwnsOne("ControlPlane.Api.Storage.Entities.IdracTarget", "Idrac", b1 =>
                        {
                            b1.Property<Guid>("HostId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasMaxLength(45)
                                .HasColumnType("character varying(45)")
                                .HasColumnName("idrac_ip");

                            b1.HasKey("HostId");

                            b1.ToTable("hosts");

                            b1.WithOwner()
                                .HasForeignKey("HostId")
                                .HasConstraintName("fk_hosts_hosts_id");
                        });

                    b.OwnsOne("ControlPlane.Api.Storage.Entities.ProxmoxTarget", "Proxmox", b1 =>
                        {
                            b1.Property<Guid>("HostId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Node")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("proxmox_node");

                            b1.Property<int>("Vmid")
                                .HasColumnType("integer")
                                .HasColumnName("proxmox_vmid");

                            b1.HasKey("HostId");

                            b1.ToTable("hosts");

                            b1.WithOwner()
                                .HasForeignKey("HostId")
                                .HasConstraintName("fk_hosts_hosts_id");
                        });

                    b.OwnsOne("ControlPlane.Api.Storage.Entities.UnifiPortTarget", "NetworkPort", b1 =>
                        {
                            b1.Property<Guid>("HostId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("PortNumber")
                                .HasColumnType("integer")
                                .HasColumnName("unifi_switch_port");

                            b1.Property<string>("SwitchMac")
                                .IsRequired()
                                .HasMaxLength(17)
                                .HasColumnType("character varying(17)")
                                .HasColumnName("unifi_switch_mac");

                            b1.HasKey("HostId");

                            b1.ToTable("hosts");

                            b1.WithOwner()
                                .HasForeignKey("HostId")
                                .HasConstraintName("fk_hosts_hosts_id");
                        });

                    b.Navigation("Agent")
                        .IsRequired();

                    b.Navigation("Idrac");

                    b.Navigation("NetworkPort");

                    b.Navigation("Proxmox");
                });

            modelBuilder.Entity("ControlPlane.Api.Storage.Entities.StepLog", b =>
                {
                    b.HasOne("ControlPlane.Api.Storage.Entities.UpdateJob", "Job")
                        .WithMany("StepLogs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_step_logs_update_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ControlPlane.Api.Storage.Entities.UpdateJob", b =>
                {
                    b.HasOne("ControlPlane.Api.Storage.Entities.Host", "TargetHost")
                        .WithMany("UpdateJobs")
                        .HasForeignKey("TargetHostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_update_jobs_hosts_target_host_id");

                    b.Navigation("TargetHost");
                });

            modelBuilder.Entity("ControlPlane.Api.Storage.Entities.Host", b =>
                {
                    b.Navigation("UpdateJobs");
                });

            modelBuilder.Entity("ControlPlane.Api.Storage.Entities.UpdateJob", b =>
                {
                    b.Navigation("StepLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
