using ControlPlane.Api.Storage;
using ControlPlane.Api.Storage.Entities;
using Microsoft.EntityFrameworkCore;
using Testcontainers.PostgreSql;
using Xunit;
using HostEntity = ControlPlane.Api.Storage.Entities.Host;

namespace ControlPlane.Api.Tests;

public class PostgresStorageTests : IAsyncLifetime
{
    private readonly PostgreSqlContainer _postgres = new PostgreSqlBuilder("postgres:16-alpine")
        .WithDatabase("controlplane")
        .WithUsername("controlplane")
        .WithPassword("secret123")
        .Build();

    public async Task InitializeAsync()
    {
        await _postgres.StartAsync();
    }

    public async Task DisposeAsync()
    {
        await _postgres.DisposeAsync();
    }

    private ControlPlaneDbContext CreateContext()
    {
        var options = new DbContextOptionsBuilder<ControlPlaneDbContext>()
            .UseNpgsql(_postgres.GetConnectionString())
            .UseSnakeCaseNamingConvention()
            .Options;

        return new ControlPlaneDbContext(options);
    }

    [Fact]
    public async Task MigrateAsync_AppliesInitialCreateMigrationSuccessfully()
    {
        using var context = CreateContext();

        // Apply migrations generated by dotnet ef
        await context.Database.MigrateAsync();

        var pendingMigrations = await context.Database.GetPendingMigrationsAsync();
        Assert.Empty(pendingMigrations);
    }

    [Fact]
    public async Task CanInsertAndQueryHost_OnPostgreSQL()
    {
        using var context = CreateContext();
        await context.Database.MigrateAsync();

        var host = new HostEntity
        {
            Id = Guid.NewGuid(),
            Hostname = "pg-k8s-master-01",
            FriendlyName = "K8s Master Primary",
            IpAddress = "192.168.10.100",
            OsFamily = "linux_debian",
            TargetType = "baremetal",
            Idrac = new IdracTarget
            {
                IpAddress = "192.168.10.200"
            },
            NetworkPort = new UnifiPortTarget
            {
                SwitchMac = "11:22:33:44:55:66",
                PortNumber = 24
            },
            Agent = new AgentState
            {
                Installed = true,
                Version = "2.0.0",
                LastSeenAt = DateTimeOffset.UtcNow,
                PendingReboot = false,
                UpgradablePackagesCount = 0
            }
        };

        context.Hosts.Add(host);
        await context.SaveChangesAsync();

        var retrieved = await context.Hosts.FirstOrDefaultAsync(h => h.Hostname == "pg-k8s-master-01");
        Assert.NotNull(retrieved);
        Assert.Equal("192.168.10.100", retrieved.IpAddress);
        Assert.NotNull(retrieved.Idrac);
        Assert.Equal("192.168.10.200", retrieved.Idrac.IpAddress);
        Assert.NotNull(retrieved.NetworkPort);
        Assert.Equal(24, retrieved.NetworkPort.PortNumber);
        Assert.NotNull(retrieved.Agent);
        Assert.True(retrieved.Agent.Installed);
        Assert.Equal("2.0.0", retrieved.Agent.Version);
    }

    [Fact]
    public async Task UniqueConstraint_HostnameAndIp_EnforcedOnPostgreSQL()
    {
        using var context = CreateContext();
        await context.Database.MigrateAsync();

        var host1 = new HostEntity
        {
            Id = Guid.NewGuid(),
            Hostname = "unique-pg-host",
            IpAddress = "192.168.10.150",
            OsFamily = "linux_debian",
            TargetType = "baremetal"
        };
        var duplicateHost = new HostEntity
        {
            Id = Guid.NewGuid(),
            Hostname = "unique-pg-host",
            IpAddress = "192.168.10.151",
            OsFamily = "linux_debian",
            TargetType = "baremetal"
        };

        context.Hosts.Add(host1);
        await context.SaveChangesAsync();

        context.Hosts.Add(duplicateHost);
        await Assert.ThrowsAsync<DbUpdateException>(() => context.SaveChangesAsync());
    }

    [Fact]
    public async Task CanInsertAndQueryUpdateJobAndStepLogs_OnPostgreSQL()
    {
        using var context = CreateContext();
        await context.Database.MigrateAsync();

        var host = new HostEntity
        {
            Id = Guid.NewGuid(),
            Hostname = "pg-target-node",
            IpAddress = "192.168.10.160",
            OsFamily = "linux_rhel",
            TargetType = "proxmox_lxc"
        };
        context.Hosts.Add(host);
        await context.SaveChangesAsync();

        var job = new UpdateJob
        {
            Id = Guid.NewGuid(),
            TargetHostId = host.Id,
            InitiatedBy = "admin@homelab.local",
            Status = "Running",
            ActiveStep = "dnf_upgrade",
            SnapshotIdentifier = "snap-2026-09-04",
            StartedAt = DateTimeOffset.UtcNow
        };
        context.UpdateJobs.Add(job);
        await context.SaveChangesAsync();

        var log = new StepLog
        {
            JobId = job.Id,
            SequenceId = 1,
            StreamType = "stdout",
            LogLine = "Upgrading packages: kernel-core, systemd...",
            Timestamp = DateTimeOffset.UtcNow
        };
        context.StepLogs.Add(log);
        await context.SaveChangesAsync();

        var queriedJob = await context.UpdateJobs
            .Include(j => j.StepLogs)
            .Include(j => j.TargetHost)
            .FirstOrDefaultAsync(j => j.Id == job.Id);

        Assert.NotNull(queriedJob);
        Assert.Equal("admin@homelab.local", queriedJob.InitiatedBy);
        Assert.Equal("pg-target-node", queriedJob.TargetHost.Hostname);
        Assert.Single(queriedJob.StepLogs);
        Assert.Equal(1, queriedJob.StepLogs.First().SequenceId);
    }
}
